=== XManticore/qr/label/label.dtd
<!ELEMENT label (height, width, qrcode, text)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT qrcode (size,x,y)>
<!ELEMENT text (ptsize,x,y)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT ptsize (#PCDATA)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>

=== XManticore/qr/label/averyAddressLabel.xml
<?xml version = "1.0"?>
<!DOCTYPE label SYSTEM "label.dtd">
<label>
	<!-- in cm -->
	<height>3.4</height>
	<width>9.91</width>
	<qrcode>
		<!-- in cm -->
		<size>3.4</size>
		<x>0</x>
		<y>0</y>
	</qrcode>
	<text>
		<!-- in pt -->
		<ptsize>250</ptsize>
		<!-- in cm -->
		<x>3.9</x>
		<y>0</y>
	</text>
</label>
