=== XManticore/qr/config/pageLayout.dtd
<!-- Describes the layout of stickers on a sticker sheet. -->
<!ELEMENT pageLayout (dimension, margin, label, labelGap, rows, columns) >

<!-- The size of the paper. -->
<!ELEMENT dimension (page_height, page_width) >

<!-- The margin along the sides of the page. -->
<!ELEMENT margin (top_margin, left_margin, bottom_margin, right_margin) >

<!-- The gap between each sticker. -->
<!ELEMENT labelGap (horizontal_gap, vertical_gap)>

<!-- The dimensions and internal layout of each sticker. -->
<!ELEMENT label (label_height, label_width, qrcode, text)>

<!-- The size and positioning of the QR code in the sticker. -->
<!ELEMENT qrcode (qr_size,qr_x,qr_y)>

<!-- The size and positioning of the text in the sticker. -->
<!ELEMENT text (text_size,text_x,text_y)>

<!-- How many rows of stickers there are on the sheet. -->
<!ELEMENT rows (#PCDATA)>

<!-- How many columns of stickers there are on the sheet. -->
<!ELEMENT columns (#PCDATA)>

<!-- These are all measured in cm  -->
<!ELEMENT label_height (#PCDATA)>
<!ELEMENT label_width (#PCDATA)>
<!ELEMENT page_height (#PCDATA)>
<!ELEMENT page_width (#PCDATA)>
<!ELEMENT qr_size (#PCDATA)>
<!ELEMENT qr_x (#PCDATA)>
<!ELEMENT qr_y (#PCDATA)>
<!ELEMENT text_x (#PCDATA)>
<!ELEMENT text_y (#PCDATA)>
<!ELEMENT top_margin (#PCDATA) >
<!ELEMENT left_margin (#PCDATA) >
<!ELEMENT bottom_margin (#PCDATA) >
<!ELEMENT right_margin (#PCDATA) >
<!ELEMENT horizontal_gap (#PCDATA) >
<!ELEMENT vertical_gap (#PCDATA) >

<!-- This is measured in pt  -->
<!ELEMENT text_size (#PCDATA)>

=== XManticore/qr/config/currentLayout.xml
<?xml version = "1.0"?>
<!DOCTYPE pageLayout SYSTEM "pageLayout.dtd">
<pageLayout>
  <dimension>
    <!-- in cm -->
    <page_height>297</page_height>
    <page_width>210</page_width>
  </dimension>
  <margin>
    <!-- in cm -->
    <top_margin>16.5</top_margin>
    <left_margin>4.55</left_margin>
    <bottom_margin>6</bottom_margin>
    <right_margin>4.55</right_margin>
  </margin>
  <label>
    <!-- in cm -->
    <label_height>34</label_height>
    <label_width>99.1</label_width>
    <qrcode>
      <!-- in cm -->
      <qr_size>34</qr_size>
      <qr_x>0</qr_x>
      <qr_y>0</qr_y>
    </qrcode>
    <text>
      <!-- in pt -->
      <text_size>250</text_size>
      <!-- in cm -->
      <text_x>39</text_x>
      <text_y>0</text_y>
    </text>
  </label>
  <labelGap>
    <!-- in cm -->
    <horizontal_gap>3.4</horizontal_gap>
    <vertical_gap>0</vertical_gap>
  </labelGap>
  <rows>16</rows>
  <columns>2</columns>
</pageLayout>
